production:
  theme_id: "live"
  password: 9087ecbf5ab66c307dd04023623c1f17
  store: little-lotus-2.myshopify.com
development:
  theme_id: 159625228
  password: 9087ecbf5ab66c307dd04023623c1f17
  store: little-lotus-2.myshopify.com
  refill_rate: 2
  bucket_size: 40
  concurrency: 4
  ignore_files:
    - .git
